import { describe, expect, it } from 'vitest';
import { BRANDS } from '@authx/core';
import { BRAND_ICONS } from '../src/ui/brand-icons.js';

/**
 * The registry and the generated artwork are two files that must agree. They
 * are regenerated by `npm run icons:brands`; this is what fails if someone adds
 * a brand and forgets to run it.
 */
describe('generated brand artwork', () => {
  it('covers every entry in the registry', () => {
    const missing = BRANDS.filter((brand) => !BRAND_ICONS[brand.slug]).map((b) => b.slug);
    expect(missing, 'run `npm run icons:brands -w @authx/extension`').toEqual([]);
  });

  it('carries no artwork for brands the registry dropped', () => {
    const known = new Set(BRANDS.map((brand) => brand.slug));
    expect(Object.keys(BRAND_ICONS).filter((slug) => !known.has(slug))).toEqual([]);
  });

  it('gives every mark a viewBox and something to draw', () => {
    for (const [slug, icon] of Object.entries(BRAND_ICONS)) {
      expect(icon.viewBox, slug).toMatch(/^-?\d+(\.\d+)? -?\d+(\.\d+)? \d+(\.\d+)? \d+(\.\d+)?$/);
      expect(icon.body.length, slug).toBeGreaterThan(8);
    }
  });

  it('gives every tinted mark a usable colour', () => {
    for (const [slug, icon] of Object.entries(BRAND_ICONS)) {
      if (icon.kind === 'color') continue;
      expect(icon.hex, slug).toMatch(/^[0-9A-F]{6}$/i);
      // A stray `#` would silently break every background that uses it.
      expect(icon.hex!.startsWith('#'), slug).toBe(false);
    }
  });

  it('gives each kind the shape its renderer expects', () => {
    for (const [slug, icon] of Object.entries(BRAND_ICONS)) {
      if (icon.kind === 'mono') {
        // A path, not markup: it goes straight into a d= attribute.
        expect(icon.body.startsWith('<'), slug).toBe(false);
        expect(icon.body, slug).toMatch(/^[Mm]/);
      } else {
        // `flat` and `color` are both markup, injected as the svg's children.
        expect(icon.body, slug).toMatch(/^</);
      }
    }
  });

  it('never leaves a mark that would be invisible on its tile', () => {
    for (const [slug, icon] of Object.entries(BRAND_ICONS)) {
      if (icon.kind !== 'color') continue;
      // Full-colour marks sit on white; one drawn entirely in white is a blank
      // square, which is worse than a letter.
      const fills = [...icon.body.matchAll(/fill="([^"]+)"/g)].map((m) => m[1]!.toLowerCase());
      const visible = fills.filter(
        (fill) => !['none', '#fff', '#ffffff', 'white'].includes(fill),
      );
      expect(fills.length === 0 || visible.length > 0, slug).toBe(true);
    }
  });

  it('marks the wordmarks the registry flagged', () => {
    for (const brand of BRANDS) {
      expect(BRAND_ICONS[brand.slug]?.wide ?? false, brand.slug).toBe(brand.wide === true);
    }
  });

  it('stays within a bundle size worth paying for', () => {
    const bytes = Object.values(BRAND_ICONS).reduce((total, icon) => total + icon.body.length, 0);
    // Around 475 KB raw for 447 services, a fraction of that after compression.
    // Worth it for a list that can be scanned by eye; worth re-examining before
    // it doubles again.
    expect(bytes).toBeLessThan(700 * 1024);
  });

  it('covers the services people are most likely to have', () => {
    for (const slug of ['github', 'google', 'apple', 'microsoft', 'aws', 'cloudflare', 'binance', 'anthropic']) {
      expect(BRAND_ICONS[slug], slug).toBeTruthy();
    }
  });
});
