/**
 * Writes Keyrook's identity kit from packages/brand/src — the one source every
 * Keyrook product takes its look from.
 *
 *   node scripts/render-brand.mjs           → packages/brand/{brand.css,assets/,guide.html}
 *   node scripts/render-brand.mjs --check   fails if any text output is stale (CI)
 *
 * brand.css is the tokens as CSS custom properties plus the hand-drawn
 * motions, for any page to import. assets/ is the logo kit as SVG and PNG.
 * guide.html is the brand book: what each piece is for, and what not to do.
 * The PNGs are left out of --check: zlib output may differ between Node
 * versions, and they are drawn from the same geometry as the SVGs beside them.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import * as brand from '../packages/brand/src/index.ts';
import { renderPng } from './raster.mjs';

const ROOT = resolve(import.meta.dirname, '..');
const OUT = join(ROOT, 'packages/brand');
const CHECK = process.argv.includes('--check');

const {
  INK, PAPER, NEUTRAL, CRAYON, ROLES, FONT, LINE, MOTION, SKETCH_RADIUS, SKETCH_RADIUS_SMALL,
  MARK_FULL, MARK_COMPACT, WORDMARK, LOCKUP_HORIZONTAL, LOCKUP_STACKED, markSvg,
  AUTHENTICATOR_MARK, AUTHENTICATOR_MARK_COMPACT,
} = brand;
const NIGHT = NEUTRAL[950];

const HEADER = '/* Generated by scripts/render-brand.mjs from packages/brand/src. Do not edit. */';

// --- brand.css ----------------------------------------------------------------

function css() {
  const lines = [HEADER, '', ':root {'];
  const v = (name, value) => lines.push(`  --kr-${name}: ${value};`);
  v('ink', INK);
  v('paper', PAPER);
  for (const [stop, hex] of Object.entries(NEUTRAL)) v(`neutral-${stop}`, hex);
  for (const [name, ramp] of Object.entries(CRAYON)) {
    for (const [stop, hex] of Object.entries(ramp)) v(`${name}-${stop}`, hex);
  }
  v('font-sans', FONT.sans);
  v('font-mono', FONT.mono);
  for (const [name, px] of Object.entries(LINE)) v(`line-${name}`, `${px}px`);
  v('radius-sketch', SKETCH_RADIUS);
  v('radius-sketch-small', SKETCH_RADIUS_SMALL);
  for (const name of ['fast', 'base', 'slow', 'draw']) v(`motion-${name}`, `${MOTION[name]}ms`);
  v('boil-step', `${MOTION.boilStep}ms`);
  v('boil-rounds', String(MOTION.boilRounds));
  v('ease-out', MOTION.easeOut);
  lines.push('');
  lines.push('  /* What a page reads. Light by default; dark below. */');
  const light = {
    page: 'var(--kr-paper)',
    surface: 'var(--kr-neutral-0)',
    text: 'var(--kr-ink)',
    'text-muted': 'var(--kr-neutral-600)',
    line: 'var(--kr-neutral-200)',
    'crow-ink': 'var(--kr-ink)',
  };
  const dark = {
    page: `var(--kr-neutral-950)`,
    surface: 'var(--kr-neutral-900)',
    text: 'var(--kr-paper)',
    'text-muted': 'var(--kr-neutral-400)',
    line: 'var(--kr-neutral-700)',
    'crow-ink': 'var(--kr-paper)',
  };
  for (const [role, { crayon, light: stop }] of Object.entries(ROLES)) light[role] = `var(--kr-${crayon}-${stop})`;
  for (const [role, { crayon, dark: stop }] of Object.entries(ROLES)) dark[role] = `var(--kr-${crayon}-${stop})`;
  for (const [name, value] of Object.entries(light)) v(name, value);
  lines.push('}', '');
  const darkBlock = (indent) =>
    Object.entries(dark).map(([name, value]) => `${indent}--kr-${name}: ${value};`);
  // Two ways in: an explicit attribute, which wins (an app's own theme
  // switch), and the system setting when a page has none.
  lines.push("[data-theme='dark'] {", ...darkBlock('  '), '}', '');
  lines.push('@media (prefers-color-scheme: dark) {', "  :root:not([data-theme='light']) {", ...darkBlock('    '), '  }', '}', '');
  lines.push(
    '/* A drawing redrawn a hair out of place three times a second, a few times,',
    '   then still. Drawings only — never text a person must read. */',
    '.kr-boil {',
    '  animation: kr-boil calc(var(--kr-boil-step) * 3) steps(1) var(--kr-boil-rounds);',
    '}',
    '',
    '.kr-boil-loop {',
    '  animation: kr-boil calc(var(--kr-boil-step) * 3) steps(1) infinite;',
    '}',
    '',
    '@keyframes kr-boil {',
    '  0% { transform: none; }',
    '  33% { transform: rotate(-1.2deg) translate(0.4px, -0.4px); }',
    '  66% { transform: rotate(0.9deg) translate(-0.4px, 0.3px); }',
    '}',
    '',
    '/* Lines drawn in by the pen, once. Each path needs pathLength="1". */',
    '.kr-draw :is(path, circle, line, polyline) {',
    '  stroke-dasharray: 1;',
    '  stroke-dashoffset: 1;',
    '  animation: kr-draw var(--kr-motion-draw) var(--kr-ease-out) forwards;',
    '}',
    '',
    '@keyframes kr-draw {',
    '  to { stroke-dashoffset: 0; }',
    '}',
    '',
    '/* A box drawn by hand. Pair with a border in var(--kr-line-pen). */',
    '.kr-sketch {',
    '  border-radius: var(--kr-radius-sketch);',
    '}',
    '',
    '.kr-sketch-small {',
    '  border-radius: var(--kr-radius-sketch-small);',
    '}',
    '',
    '@media (prefers-reduced-motion: reduce) {',
    '  .kr-boil,',
    '  .kr-boil-loop,',
    '  .kr-draw :is(path, circle, line, polyline) {',
    '    animation: none;',
    '    stroke-dashoffset: 0;',
    '  }',
    '}',
    '',
  );
  return lines.join('\n');
}

// --- assets -------------------------------------------------------------------

const SVGS = {
  'keyrook-mark.svg': () => markSvg(MARK_FULL, { title: 'Keyrook' }),
  'keyrook-mark-on-dark.svg': () => markSvg(MARK_FULL, { title: 'Keyrook', ink: PAPER }),
  'keyrook-mark-sticker.svg': () => markSvg(MARK_FULL, { title: 'Keyrook', sticker: true }),
  'keyrook-mark-compact.svg': () => markSvg(MARK_COMPACT, { title: 'Keyrook', sticker: true }),
  'keyrook-mark-ink.svg': () => markSvg(MARK_FULL, { title: 'Keyrook', mono: INK }),
  'keyrook-mark-paper.svg': () => markSvg(MARK_FULL, { title: 'Keyrook', mono: PAPER }),
  'keyrook-wordmark.svg': () => markSvg(WORDMARK, { title: 'Keyrook' }),
  'keyrook-wordmark-on-dark.svg': () => markSvg(WORDMARK, { title: 'Keyrook', ink: PAPER }),
  'keyrook-lockup.svg': () => markSvg(LOCKUP_HORIZONTAL, { title: 'Keyrook' }),
  'keyrook-lockup-on-dark.svg': () => markSvg(LOCKUP_HORIZONTAL, { title: 'Keyrook', ink: PAPER }),
  'keyrook-lockup-stacked.svg': () => markSvg(LOCKUP_STACKED, { title: 'Keyrook' }),
  'keyrook-lockup-stacked-on-dark.svg': () => markSvg(LOCKUP_STACKED, { title: 'Keyrook', ink: PAPER }),
  // Products. Each has its own mark; none wears the crow.
  'authenticator-mark.svg': () => markSvg(AUTHENTICATOR_MARK, { title: 'Keyrook Authenticator' }),
  'authenticator-mark-compact.svg': () => markSvg(AUTHENTICATOR_MARK_COMPACT, { title: 'Keyrook Authenticator' }),
};

const PNGS = {
  'keyrook-mark-512.png': () => renderPng(MARK_FULL, { width: 512, sticker: true }),
  'keyrook-mark-1024.png': () => renderPng(MARK_FULL, { width: 1024, sticker: true }),
  // A profile picture: the crow on paper, filling the circle a platform crops to.
  'keyrook-avatar-1024.png': () =>
    renderPng({ ...MARK_FULL, view: [-6, 1, 116, 116] }, { width: 1024, background: PAPER }),
  'keyrook-lockup-1200.png': () => renderPng(LOCKUP_HORIZONTAL, { width: 1200 }),
  'keyrook-lockup-on-dark-1200.png': () => renderPng(LOCKUP_HORIZONTAL, { width: 1200, ink: PAPER }),
  'keyrook-lockup-stacked-1024.png': () => renderPng(LOCKUP_STACKED, { width: 1024 }),
  'authenticator-mark-512.png': () => renderPng(AUTHENTICATOR_MARK, { width: 512 }),
};

// --- guide.html ---------------------------------------------------------------

function swatch(hex, label) {
  return `<div class="sw"><div class="chip" style="background:${hex}"></div><b>${label}</b><code>${hex}</code></div>`;
}

function guide(cssText) {
  const ramps = Object.entries(CRAYON)
    .map(
      ([name, ramp]) =>
        `<div class="ramp"><b>${name}</b><div class="stops">${Object.entries(ramp)
          .map(
            ([stop, hex]) =>
              `<div title="${hex}" style="background:${hex};color:${Number(stop) >= 500 && name !== 'yellow' ? PAPER : INK}">${stop}</div>`,
          )
          .join('')}</div></div>`,
    )
    .join('');
  const neutrals = Object.entries(NEUTRAL)
    .map(([stop, hex]) => `<div title="${hex}" style="background:${hex};color:${Number(stop) >= 500 ? PAPER : INK}">${stop}</div>`)
    .join('');
  const roles = Object.entries(ROLES)
    .map(
      ([role, { crayon, light, dark }]) =>
        `<tr><td><b>${role}</b></td><td>${crayon}</td><td><span class="dot" style="background:${CRAYON[crayon][light]}"></span>${light} <code>${CRAYON[crayon][light]}</code></td><td><span class="dot" style="background:${CRAYON[crayon][dark]}"></span>${dark} <code>${CRAYON[crayon][dark]}</code></td></tr>`,
    )
    .join('');
  const drawn = (mark, options) => markSvg(mark, { ink: 'currentColor', ...options });

  return `<!doctype html>
<!-- Generated by scripts/render-brand.mjs from packages/brand/src. Do not edit. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Keyrook brand</title>
<style>
${cssText.replace(HEADER, '').trim()}

* { box-sizing: border-box; }
body { margin: 0; background: var(--kr-page); color: var(--kr-text); font: 16px/1.6 var(--kr-font-sans); }
main { max-width: 960px; margin: 0 auto; padding: 48px 16px 96px; }
h1 { font-size: 32px; font-weight: 600; margin: 24px 0 8px; }
h2 { font-size: 22px; font-weight: 600; margin: 64px 0 8px; padding-top: 16px; border-top: 2px solid var(--kr-line); }
h3 { font-size: 16px; font-weight: 600; margin: 24px 0 8px; }
p, li { max-width: 68ch; }
.muted { color: var(--kr-text-muted); }
code { font-family: var(--kr-font-mono); font-size: 13px; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin: 16px 0; }
.tile { border: var(--kr-line-pen) solid var(--kr-line); padding: 20px; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 12px; min-height: 200px; }
.tile.paper { background: ${PAPER}; color: ${INK}; }
.tile.night { background: ${NIGHT}; color: ${PAPER}; }
.tile.photo { background: repeating-linear-gradient(45deg, ${CRAYON.blue[300]} 0 14px, ${CRAYON.green[300]} 14px 28px); color: ${INK}; }
.tile small { font-size: 13px; opacity: .8; }
.tile svg { max-width: 100%; height: auto; }
.sizes { display: flex; gap: 20px; align-items: flex-end; flex-wrap: wrap; }
.sw { display: flex; flex-direction: column; gap: 2px; }
.chip { height: 72px; border: 1px solid var(--kr-line); margin-bottom: 6px; }
.ramp { margin: 12px 0; }
.stops { display: grid; grid-template-columns: repeat(10, 1fr); }
.stops div { height: 48px; display: flex; align-items: end; padding: 4px; font: 11px var(--kr-font-mono); }
table { border-collapse: collapse; width: 100%; font-size: 14px; }
td, th { text-align: start; padding: 8px; border-bottom: 1px solid var(--kr-line); }
.dot { display: inline-block; width: 12px; height: 12px; border-radius: 50%; margin-inline-end: 6px; vertical-align: -1px; }
.dont { border-color: ${CRAYON.red[500]}; }
.dont small::before { content: "✕ "; color: ${CRAYON.red[600]}; font-weight: 700; }
.do small::before { content: "✓ "; color: ${CRAYON.green[600]}; font-weight: 700; }
.code { font: 600 34px var(--kr-font-mono); letter-spacing: 3px; }
.sketchbox { border: var(--kr-line-pen) solid var(--kr-text); padding: 16px 20px; }
button.kr { font: inherit; background: var(--kr-action); color: ${PAPER}; border: 0; padding: 10px 18px; cursor: pointer; }
.replay { font: inherit; font-size: 14px; background: none; border: 1px solid var(--kr-line); color: inherit; padding: 6px 12px; cursor: pointer; border-radius: 6px; }
@media (max-width: 600px) { .stops div { font-size: 0; } }
</style>
</head>
<body>
<main>
${markSvg(LOCKUP_HORIZONTAL, { ink: 'currentColor', width: 300, title: 'Keyrook' }).replace('<svg ', '<svg class="kr-boil" ')}
<h1>Keyrook brand</h1>
<p class="muted">One look for every Keyrook product — Keyrook Authenticator, the website, and the apps after it. Everything on this page is generated from <code>packages/brand/src</code>; the files it shows are in <code>packages/brand/assets</code>, and <code>packages/brand/brand.css</code> gives any page the same colours and movements.</p>

<h2>The crow</h2>
<p>A <i>rook</i> is two things: the chess piece the name suggests, and a bird of the crow family. Crows are known for picking things up and keeping them. Ours keeps a key. Its feathers are four crayons — the colours the product has always had — and its eye is the same yellow as the key.</p>
<p>Keyrook is drawn by hand: ink on paper, crayon colour, lines that wobble a little. It is plain and a bit rough on purpose. A security product that looks like a person made it is easier to trust than one that looks like a vault door.</p>

<h2>Logo</h2>
<div class="grid">
<div class="tile paper">${drawn(MARK_FULL, { width: 140 })}<small>On paper — the default</small></div>
<div class="tile night">${drawn(MARK_FULL, { width: 140 })}<small>On night — the crow turns paper</small></div>
<div class="tile photo">${drawn(MARK_FULL, { width: 140, ink: INK, sticker: true })}<small>Sticker — on anything busy</small></div>
<div class="tile paper">${drawn(MARK_FULL, { width: 140, mono: INK })}<small>One colour — stamps, engraving</small></div>
</div>
<div class="grid">
<div class="tile paper">${drawn(LOCKUP_HORIZONTAL, { width: 280 })}<small>Lockup — headers, the website</small></div>
<div class="tile night">${drawn(LOCKUP_STACKED, { width: 150 })}<small>Stacked — square spaces, splash</small></div>
</div>
<h3>Two drawings, by size</h3>
<p>Below 32 px the compact crow is used: no feet, two broad feathers, a bigger key. At 16 px a foot is a fifth of a pixel and four feathers are one smudge. <code>markFor(px)</code> picks the right one.</p>
<div class="tile paper" style="min-height:0"><div class="sizes">
${[16, 24].map((s) => drawn(MARK_COMPACT, { width: s, sticker: true })).join('')}
${[32, 48, 64, 96, 128].map((s) => drawn(MARK_FULL, { width: s })).join('')}
</div></div>
<h3>Room and size</h3>
<ul>
<li>Clear space round the crow: at least the width of the key on every side.</li>
<li>Smallest: the crow at 16 px (compact), the lockup at 120 px wide. Below that, use the crow alone.</li>
<li>The wordmark is lettered, not typed. Never set "keyrook" in a font to stand in for it.</li>
</ul>
<h3>Don't</h3>
<div class="grid">
<div class="tile paper dont">${drawn(MARK_FULL, { width: 110, ink: CRAYON.blue[500] })}<small>Recolour the crow</small></div>
<div class="tile paper dont" style="transform:none">${drawn(MARK_FULL, { width: 110 }).replace('<svg ', '<svg style="transform:scaleX(1.4)" ')}<small>Stretch it</small></div>
<div class="tile paper dont">${drawn(MARK_FULL, { width: 110, mono: '#4285F4' })}<small>Use Google's colours</small></div>
<div class="tile photo dont">${drawn(MARK_FULL, { width: 110, ink: INK })}<small>Busy ground, no sticker</small></div>
</div>

<h2>The family</h2>
<p>The crow is Keyrook's, and only Keyrook's. It appears where the brand itself speaks: the Keyrook account every product signs in to, the emails it sends, Keyrook's own site, and a small "by Keyrook" at the foot of a product's page. A product never wears it as its icon.</p>
<p>Each product has its own mark, drawn in the same hand with the same four crayons, so the family shows without one member borrowing another's face. Its name is Keyrook and what it does.</p>
<div class="grid">
<div class="tile paper">${drawn(MARK_FULL, { width: 110 })}<small>Keyrook — the brand</small></div>
<div class="tile paper do">${drawn(AUTHENTICATOR_MARK, { width: 110 })}<small>Keyrook Authenticator</small></div>
<div class="tile paper" style="border-style:dashed"><div style="width:110px;height:110px"></div><small>The next product — its own mark</small></div>
</div>
<h3>Keyrook Authenticator</h3>
<p>The countdown asterisk the extension has always had — eight ticks round a centre, like the dial of the 30-second timer every code runs on, and like the asterisks that mask a password — redrawn by hand in Keyrook's crayons. They run blue, yellow, red, green clockwise from twelve — warm pair together, cool pair together: neither Google's order, in either direction, nor Google's colours, which is what keeps eight coloured ticks from reading as theirs. Below 32 px the compact drawing, straighter and thicker. <code>authenticatorMarkFor(px)</code> picks it.</p>
<div class="tile paper" style="min-height:0"><div class="sizes">
${[16, 24].map((s) => drawn(AUTHENTICATOR_MARK_COMPACT, { width: s })).join('')}
${[32, 48, 64, 96, 128].map((s) => drawn(AUTHENTICATOR_MARK, { width: s })).join('')}
</div></div>
<div class="tile night" style="min-height:0"><div class="sizes">
${[16, 24].map((s) => drawn(AUTHENTICATOR_MARK_COMPACT, { width: s })).join('')}
${[32, 48, 64, 96, 128].map((s) => drawn(AUTHENTICATOR_MARK, { width: s })).join('')}
</div></div>
<h3>Don't</h3>
<div class="grid">
<div class="tile paper dont"><div style="display:flex;gap:10px;align-items:center">${drawn(MARK_FULL, { width: 48 })}<b>Keyrook Authenticator</b></div><small>Give a product the crow</small></div>
<div class="tile paper dont"><div style="display:flex;gap:10px;align-items:center">${drawn(AUTHENTICATOR_MARK, { width: 48 })}<b>Keyrook</b></div><small>Call a product just "Keyrook"</small></div>
</div>

<h2>Colour</h2>
<p>Ink and paper first; colour is crayon, used sparingly, and every crayon has one job in every product.</p>
<div class="grid">
${swatch(INK, 'Ink')}${swatch(PAPER, 'Paper')}${swatch(NIGHT, 'Night')}
${Object.entries(CRAYON).map(([name, ramp]) => swatch(ramp[500], name[0].toUpperCase() + name.slice(1))).join('')}
</div>
<h3>Roles</h3>
<table><thead><tr><th>Role</th><th>Crayon</th><th>Text on light</th><th>Text on dark</th></tr></thead><tbody>${roles}</tbody></table>
<p class="muted">Action is blue, danger red, warning yellow, success green — the same in the extension, the site and any app. Red, yellow and green at 500 are too light for text on paper; they colour marks and fills, and text uses the stop in the table, which holds 4.5:1.</p>
<h3>Ramps</h3>
${ramps}
<div class="ramp"><b>neutral</b><div class="stops" style="grid-template-columns:repeat(12,1fr)">${neutrals}</div></div>

<h2>Type</h2>
<p>Keyrook has no handwriting font. The hand shows in what is drawn — the crow, the wordmark, lines and boxes. Words stay in the system's own faces, so all fifty languages look like one product, and none falls back to a stranger's font halfway through a sentence.</p>
<table>
<tr><td><b>Text</b></td><td style="font-family:var(--kr-font-sans)">The quick brown fox — Chữ tiếng Việt — 日本語 — العربية</td></tr>
<tr><td><b>Codes</b></td><td><span class="code">482 913</span></td></tr>
</table>
<p class="muted"><code>--kr-font-sans</code>, <code>--kr-font-mono</code>. Codes, addresses and recovery keys are mono, straight and still: a person reads them and types them somewhere else.</p>

<h2>Lines and boxes</h2>
<p>Three pen weights for drawn things — <code>--kr-line-hair</code> ${LINE.hair}px, <code>--kr-line-pen</code> ${LINE.pen}px, <code>--kr-line-marker</code> ${LINE.marker}px at a 24 px icon. A box is drawn by hand with <code>.kr-sketch</code>: four corners that are not quite the same.</p>
<div class="grid">
<div class="sketchbox kr-sketch">A card drawn by hand.</div>
<div><button class="kr kr-sketch-small">Copy code</button></div>
</div>

<h2>Motion</h2>
<p>Two movements belong to Keyrook, both from hand-drawn animation, and the plain ones under them.</p>
<div class="grid">
<div class="tile paper"><svg id="draw" class="kr-draw" viewBox="0 0 100 60" width="200" fill="none" stroke="${INK}" stroke-width="3" stroke-linecap="round"><path pathLength="1" d="M8 40 C25 10 45 10 55 30 C62 44 78 48 92 22"/></svg><small>Draw — a line drawn in by the pen, once</small><button class="replay" data-replay="draw">Again</button></div>
<div class="tile paper"><div id="boil" class="kr-boil">${drawn(MARK_FULL, { width: 110 })}</div><small>Boil — redrawn a hair out of place, a few times, then still</small><button class="replay" data-replay="boil">Again</button></div>
</div>
<table>
<tr><td><b>fast</b></td><td><code>${MOTION.fast}ms</code></td><td>a press, a toggle</td></tr>
<tr><td><b>base</b></td><td><code>${MOTION.base}ms</code></td><td>a sheet opening, a toast</td></tr>
<tr><td><b>slow</b></td><td><code>${MOTION.slow}ms</code></td><td>a screen arriving</td></tr>
<tr><td><b>draw</b></td><td><code>${MOTION.draw}ms</code></td><td>a line drawn in</td></tr>
<tr><td><b>boil</b></td><td><code>${MOTION.boilStep}ms × 3, ${MOTION.boilRounds} rounds</code></td><td>a drawing settling in</td></tr>
<tr><td><b>ease</b></td><td colspan="2"><code>${MOTION.easeOut}</code></td></tr>
</table>
<ul>
<li>Drawings move; text a person must read never does. A code that wobbles is a code read wrong.</li>
<li>Movement is brief and on arrival. Nothing loops forever except where something is genuinely waiting.</li>
<li>Only transform and opacity: nothing that moves the layout round it.</li>
<li><code>prefers-reduced-motion</code> stops all of it. <code>brand.css</code> already does.</li>
</ul>

<h2>Words</h2>
<ul>
<li><b>Keyrook</b> is the brand, and names only what Keyrook products share: the account ("a Keyrook account"), the email sender.</li>
<li>Each product is <b>Keyrook</b> + what it does: <b>Keyrook Authenticator</b>. The name is never translated.</li>
<li>Plain and honest about limits. No "military-grade", no "unhackable".</li>
<li>Every word a person reads lives in a language file, the same keys in every language, so all languages say the same thing.</li>
</ul>

<h2>Using it</h2>
<p>In a product in this repository:</p>
<pre><code>import { markFor, markSvg, CRAYON } from '@keyrook/brand';
@import '…/packages/brand/brand.css';   /* --kr-* and .kr-boil, .kr-draw, .kr-sketch */</code></pre>
<p>Anywhere else: the files in <code>packages/brand/assets</code>, and the values on this page.</p>
</main>
<script>
document.querySelectorAll('[data-replay]').forEach((button) => {
  button.addEventListener('click', () => {
    const target = document.getElementById(button.dataset.replay);
    const name = target.getAttribute('class');
    target.setAttribute('class', '');
    void target.getBoundingClientRect();
    target.setAttribute('class', name);
  });
});
</script>
</body>
</html>
`;
}

// --- write or check -------------------------------------------------------------

const cssText = css();
const texts = {
  'brand.css': cssText,
  'guide.html': guide(cssText),
  ...Object.fromEntries(Object.entries(SVGS).map(([name, make]) => [`assets/${name}`, `${make()}\n`])),
};

let stale = 0;
for (const [path, content] of Object.entries(texts)) {
  const file = join(OUT, path);
  if (CHECK) {
    let current = null;
    try {
      current = readFileSync(file, 'utf8');
    } catch {}
    if (current !== content) {
      console.error(`✗ ${relative(ROOT, file)} is stale — run node scripts/render-brand.mjs`);
      stale++;
    }
    continue;
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  console.log(`✓ ${relative(ROOT, file)}`);
}

if (CHECK) {
  if (stale) process.exit(1);
  console.log('✓ brand kit is current');
} else {
  for (const [name, make] of Object.entries(PNGS)) {
    const file = join(OUT, 'assets', name);
    writeFileSync(file, make());
    console.log(`✓ ${relative(ROOT, file)}`);
  }
}
