/**
 * Writes Keyrook's identity kit from packages/brand/src — the one source every
 * Keyrook product takes its look from.
 *
 *   node scripts/render-brand.mjs           → packages/brand/{brand.css,assets/,guide.html}
 *   node scripts/render-brand.mjs --check   fails if any text output is stale (CI)
 *
 * brand.css is the tokens as CSS custom properties plus the hand-drawn
 * motions, for any page to import. assets/ is the logo kit as SVG and PNG.
 * guide.html is the brand book: what each piece is for, and what not to do.
 * The PNGs are left out of --check: zlib output may differ between Node
 * versions, and they are drawn from the same geometry as the SVGs beside them.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import * as brand from '../packages/brand/src/index.ts';
import { renderPng } from './raster.mjs';

const ROOT = resolve(import.meta.dirname, '..');
const OUT = join(ROOT, 'packages/brand');
const CHECK = process.argv.includes('--check');

const {
  INK, PAPER, NEUTRAL, CRAYON, ROLES, FONT, LINE, MOTION, SKETCH_RADIUS, SKETCH_RADIUS_SMALL,
  SKETCH_RADIUS_ALT, SKETCH_RADIUS_SMALL_ALT, SPACE, TYPE, ELEVATION,
  MARK_FULL, MARK_COMPACT, WORDMARK, LOCKUP_HORIZONTAL, LOCKUP_STACKED, markSvg,
  AUTHENTICATOR_MARK, AUTHENTICATOR_MARK_COMPACT,
  ICONS, ICON_GROUPS, ICON_STROKE, iconSvg, iconElements, letter,
} = brand;
const NIGHT = NEUTRAL[950];

const HEADER = '/* Generated by scripts/render-brand.mjs from packages/brand/src. Do not edit. */';

// --- brand.css ----------------------------------------------------------------

function css() {
  const lines = [HEADER, '', ':root {'];
  const v = (name, value) => lines.push(`  --kr-${name}: ${value};`);
  v('ink', INK);
  v('paper', PAPER);
  for (const [stop, hex] of Object.entries(NEUTRAL)) v(`neutral-${stop}`, hex);
  for (const [name, ramp] of Object.entries(CRAYON)) {
    for (const [stop, hex] of Object.entries(ramp)) v(`${name}-${stop}`, hex);
  }
  v('font-sans', FONT.sans);
  v('font-mono', FONT.mono);
  for (const [name, px] of Object.entries(LINE)) v(`line-${name}`, `${px}px`);
  v('radius-sketch', SKETCH_RADIUS);
  v('radius-sketch-small', SKETCH_RADIUS_SMALL);
  v('radius-sketch-alt', SKETCH_RADIUS_ALT);
  v('radius-sketch-small-alt', SKETCH_RADIUS_SMALL_ALT);
  for (const [step, px] of Object.entries(SPACE)) v(`space-${step}`, `${px}px`);
  for (const name of ['fast', 'base', 'slow', 'draw']) v(`motion-${name}`, `${MOTION[name]}ms`);
  for (const name of ['stagger', 'wait', 'hold', 'toast']) v(`motion-${name}`, `${MOTION[name]}ms`);
  v('boil-step', `${MOTION.boilStep}ms`);
  v('boil-rounds', String(MOTION.boilRounds));
  v('ease-out', MOTION.easeOut);
  v('ease-in', MOTION.easeIn);
  v('ease-in-out', MOTION.easeInOut);
  v('ease-settle', MOTION.easeSettle);
  lines.push('');
  lines.push('  /* What a page reads. Light by default; dark below. */');
  const shadow = (scheme) =>
    Object.fromEntries(
      Object.entries(ELEVATION).map(([name, e]) => [`shadow-${name}`, `${e.x}px ${e.y}px 0 ${e[scheme]}`]),
    );
  const light = {
    page: 'var(--kr-paper)',
    surface: 'var(--kr-neutral-0)',
    'surface-sunken': 'var(--kr-neutral-100)',
    text: 'var(--kr-ink)',
    'text-muted': 'var(--kr-neutral-600)',
    line: 'var(--kr-neutral-200)',
    // A field's edge has to hold 3:1 against the page to be seen as one; --kr-line is for decoration.
    'line-strong': 'var(--kr-neutral-500)',
    'crow-ink': 'var(--kr-ink)',
    focus: 'var(--kr-blue-500)',
    // Crayon laid behind words: the words stay ink and stay readable on it.
    highlight: 'var(--kr-yellow-200)',
    ...shadow('light'),
  };
  const dark = {
    page: `var(--kr-neutral-950)`,
    surface: 'var(--kr-neutral-900)',
    'surface-sunken': 'var(--kr-neutral-800)',
    text: 'var(--kr-paper)',
    'text-muted': 'var(--kr-neutral-400)',
    line: 'var(--kr-neutral-700)',
    'line-strong': 'var(--kr-neutral-400)',
    'crow-ink': 'var(--kr-paper)',
    focus: 'var(--kr-blue-300)',
    highlight: 'var(--kr-yellow-900)',
    ...shadow('dark'),
  };
  for (const [role, { crayon, light: stop }] of Object.entries(ROLES)) light[role] = `var(--kr-${crayon}-${stop})`;
  for (const [role, { crayon, dark: stop }] of Object.entries(ROLES)) dark[role] = `var(--kr-${crayon}-${stop})`;
  for (const [name, value] of Object.entries(light)) v(name, value);
  lines.push('}', '');
  const darkBlock = (indent) =>
    Object.entries(dark).map(([name, value]) => `${indent}--kr-${name}: ${value};`);
  // Two ways in: an explicit attribute, which wins (an app's own theme
  // switch), and the system setting when a page has none.
  lines.push("[data-theme='dark'] {", ...darkBlock('  '), '}', '');
  lines.push('@media (prefers-color-scheme: dark) {', "  :root:not([data-theme='light']) {", ...darkBlock('    '), '  }', '}', '');
  lines.push(
    '/* A drawing redrawn a hair out of place three times a second, a few times,',
    '   then still. Drawings only — never text a person must read. */',
    '.kr-boil {',
    '  animation: kr-boil calc(var(--kr-boil-step) * 3) steps(1) var(--kr-boil-rounds);',
    '}',
    '',
    '.kr-boil-loop {',
    '  animation: kr-boil calc(var(--kr-boil-step) * 3) steps(1) infinite;',
    '}',
    '',
    '@keyframes kr-boil {',
    '  0% { transform: none; }',
    '  33% { transform: rotate(-1.2deg) translate(0.4px, -0.4px); }',
    '  66% { transform: rotate(0.9deg) translate(-0.4px, 0.3px); }',
    '}',
    '',
    '/* Lines drawn in by the pen, once. Each path needs pathLength="1". */',
    '.kr-draw :is(path, circle, line, polyline) {',
    '  stroke-dasharray: 1;',
    '  stroke-dashoffset: 1;',
    '  animation: kr-draw var(--kr-motion-draw) var(--kr-ease-out) forwards;',
    '}',
    '',
    '@keyframes kr-draw {',
    '  to { stroke-dashoffset: 0; }',
    '}',
    '',
    '/* A box drawn by hand. Pair with a border in var(--kr-line-pen). */',
    '.kr-sketch {',
    '  border-radius: var(--kr-radius-sketch);',
    '}',
    '',
    '.kr-sketch-small {',
    '  border-radius: var(--kr-radius-sketch-small);',
    '}',
    '',
    ...extras(),
    '@media (prefers-reduced-motion: reduce) {',
    '  .kr-boil,',
    '  .kr-boil-loop,',
    '  .kr-draw :is(path, circle, line, polyline),',
    '  .kr-arrive,',
    '  .kr-stagger > *,',
    '  .kr-appear,',
    '  .kr-pop,',
    '  .kr-highlight,',
    '  .kr-wait path,',
    '  .kr-blink > circle {',
    '    animation: none;',
    '    stroke-dashoffset: 0;',
    '  }',
    '',
    '  /* Still ends gone, only without the going. */',
    '  .kr-leave {',
    '    animation-duration: 1ms;',
    '  }',
    '',
    '  .kr-press,',
    '  .kr-press:active {',
    '    transform: none;',
    '    transition: none;',
    '  }',
    '}',
    '',
  );
  return lines.join('\n');
}

/**
 * Everything brand.css gives a page beyond the two drawn motions: the type
 * scale, boxes and height, icons, and the plain motions under the drawn ones.
 * Classes, not inline styles, so a page under a strict Content Security
 * Policy (keyrook.com allows one stylesheet by hash) can use all of it.
 */
function extras() {
  const out = [];
  const add = (...more) => out.push(...more);
  const round = (value) => Math.round(value * 100) / 100;

  add("/* The type scale, in the system's faces. Codes are mono, tabular, and", '   left to right even on a right-to-left page: a code read backwards is a wrong code. */');
  for (const [name, t] of Object.entries(TYPE)) {
    add(`.kr-${name} {`, `  font: ${t.weight} ${t.size}px/${t.line}px var(--kr-font-${t.mono ? 'mono' : 'sans'});`);
    if (t.tracking) add(`  letter-spacing: ${t.tracking}em;`);
    if (t.mono) add('  font-variant-numeric: tabular-nums;', '  direction: ltr;', '  unicode-bidi: isolate;');
    add('}', '');
  }
  const tight = Object.entries(TYPE).filter(([, t]) => !t.mono && t.tracking < 0).map(([name]) => `.kr-${name}`);
  add(
    '/* Tightening cuts the joins of Arabic script and crowds CJK and Thai. */',
    `:is(${tight.join(', ')}):is(:lang(ar), :lang(fa), :lang(ur), :lang(ja), :lang(ko), :lang(zh), :lang(th)) {`,
    '  letter-spacing: 0;',
    '}',
    '',
    '/* Vietnamese stacks a tone on a hat (ế, ỗ); a tight heading needs room above. */',
  );
  for (const [name, t] of Object.entries(TYPE)) {
    if (t.mono || t.line / t.size >= 1.15) continue;
    add(`.kr-${name}:lang(vi) {`, `  line-height: ${Math.ceil((t.size * 1.15) / 2) * 2}px;`, '}', '');
  }

  add(
    '/* The second of two boxes side by side, so neighbours never wobble alike. */',
    '.kr-sketch-alt {',
    '  border-radius: var(--kr-radius-sketch-alt);',
    '}',
    '',
    '.kr-sketch-small-alt {',
    '  border-radius: var(--kr-radius-sketch-small-alt);',
    '}',
    '',
    '/* Height is cut paper: an ink line and a hard shadow, never a blur. */',
    '.kr-raised {',
    '  box-shadow: var(--kr-shadow-raised);',
    '}',
    '',
    '.kr-floating {',
    '  box-shadow: var(--kr-shadow-floating);',
    '}',
    '',
    '/* An icon from iconSvg() or assets/icons. The size class sets the line for',
    '   the size, so a 16 px icon is drawn at 1.5 px rather than a thinned 2. */',
    '.kr-icon {',
    '  flex-shrink: 0;',
    '  fill: none;',
    '  stroke: currentColor;',
    '  stroke-linecap: round;',
    '  stroke-linejoin: round;',
    '}',
    '',
  );
  for (const [size, px] of Object.entries(ICON_STROKE)) {
    add(`.kr-icon-${size} {`, `  width: ${size}px;`, `  height: ${size}px;`, `  stroke-width: ${round((px * 24) / Number(size))};`, '}', '');
  }
  add(
    '/* Arrows and chevrons point the way the page reads. */',
    "[dir='rtl'] .kr-icon-flip {",
    '  transform: scaleX(-1);',
    '}',
    '',
    '/* Arriving: up 8 px out of nothing, once. On a list, .kr-stagger: its items',
    '   arrive 40 ms apart, the seventh and after with the sixth. */',
    '.kr-arrive,',
    '.kr-stagger > * {',
    '  animation: kr-arrive var(--kr-motion-slow) var(--kr-ease-out) both;',
    '}',
    '',
  );
  for (let n = 2; n <= 6; n++) {
    add(`.kr-stagger > :nth-child(${n}) {`, `  animation-delay: calc(var(--kr-motion-stagger) * ${n - 1});`, '}', '');
  }
  add(
    '.kr-stagger > :nth-child(n + 7) {',
    '  animation-delay: calc(var(--kr-motion-stagger) * 5);',
    '}',
    '',
    '@keyframes kr-arrive {',
    '  from { opacity: 0; transform: translateY(8px); }',
    '}',
    '',
    '/* Shown in place: content that changes where it stands — a new code. */',
    '.kr-appear {',
    '  animation: kr-appear var(--kr-motion-base) var(--kr-ease-out) both;',
    '}',
    '',
    '@keyframes kr-appear {',
    '  from { opacity: 0; }',
    '}',
    '',
    '/* Going is quicker than coming, and only fades. */',
    '.kr-leave {',
    '  animation: kr-leave calc(var(--kr-motion-slow) * 0.6) var(--kr-ease-in) both;',
    '}',
    '',
    '@keyframes kr-leave {',
    '  to { opacity: 0; }',
    '}',
    '',
    '/* A small drawn thing landing like a stamp. Never a block of text. */',
    '.kr-pop {',
    '  animation: kr-pop var(--kr-motion-base) var(--kr-ease-settle) both;',
    '}',
    '',
    '@keyframes kr-pop {',
    '  from { opacity: 0; transform: scale(0.6); }',
    '}',
    '',
    '/* Pressed: down at once, back with a little give. */',
    '.kr-press {',
    '  transition: transform var(--kr-motion-base) var(--kr-ease-settle);',
    '}',
    '',
    '.kr-press:active {',
    '  transform: scale(0.97);',
    '  transition-duration: var(--kr-motion-fast);',
    '  transition-timing-function: var(--kr-ease-out);',
    '}',
    '',
    '/* Crayon laid behind a word once the word has landed, the way the page reads. */',
    '.kr-highlight {',
    '  transform-origin: 0 50%;',
    '  animation: kr-highlight var(--kr-motion-slow) var(--kr-ease-out) var(--kr-motion-base) both;',
    '}',
    '',
    "[dir='rtl'] .kr-highlight {",
    '  transform-origin: 100% 50%;',
    '}',
    '',
    '@keyframes kr-highlight {',
    '  from { transform: scaleX(0); }',
    '}',
    '',
    '/* With .kr-draw: the lines one after another in the order they sit, which',
    '   is the order a hand drew them. markSvg(…, { drawable: true }) writes them so. */',
  );
  for (let n = 2; n <= 24; n++) {
    add(
      `.kr-draw-in-turn :nth-child(${n} of :is(path, circle, line, polyline)) {`,
      `  animation-delay: calc(var(--kr-motion-stagger) * ${round((n - 1) * 1.5)});`,
      '}',
      '',
    );
  }
  add(
    '/* Waiting, in place of a spinner: the Authenticator mark (markSvg, no sticker)',
    '   lights its ticks in turn, clockwise from twelve. Only while something is',
    '   genuinely being waited on, and only once --kr-motion-wait has passed. */',
    '.kr-wait path {',
    '  animation: kr-wait calc(var(--kr-boil-step) * 8) steps(1) infinite;',
    '}',
    '',
  );
  for (let n = 2; n <= 8; n++) {
    add(`.kr-wait path:nth-of-type(${n}) {`, `  animation-delay: calc(var(--kr-boil-step) * ${n - 1});`, '}', '');
  }
  add(
    '@keyframes kr-wait {',
    '  0% { opacity: 1; }',
    '  12.5% { opacity: 0.55; }',
    '  25%, 100% { opacity: 0.25; }',
    '}',
    '',
    "/* The crow blinks once, two seconds after its page settles: Keyrook's own",
    '   pages only, never a product. Its eye is its first circle. */',
    '.kr-blink > circle:first-of-type {',
    '  transform-box: fill-box;',
    '  transform-origin: center;',
    '  animation: kr-blink 160ms var(--kr-ease-in-out) 2s 1;',
    '}',
    '',
    '@keyframes kr-blink {',
    '  50% { transform: scaleY(0.1); }',
    '}',
    '',
  );
  return out;
}

// --- assets -------------------------------------------------------------------

const SVGS = {
  'keyrook-mark.svg': () => markSvg(MARK_FULL, { title: 'Keyrook' }),
  'keyrook-mark-on-dark.svg': () => markSvg(MARK_FULL, { title: 'Keyrook', ink: PAPER }),
  'keyrook-mark-sticker.svg': () => markSvg(MARK_FULL, { title: 'Keyrook', sticker: true }),
  'keyrook-mark-compact.svg': () => markSvg(MARK_COMPACT, { title: 'Keyrook', sticker: true }),
  'keyrook-mark-ink.svg': () => markSvg(MARK_FULL, { title: 'Keyrook', mono: INK }),
  'keyrook-mark-paper.svg': () => markSvg(MARK_FULL, { title: 'Keyrook', mono: PAPER }),
  'keyrook-wordmark.svg': () => markSvg(WORDMARK, { title: 'Keyrook' }),
  'keyrook-wordmark-on-dark.svg': () => markSvg(WORDMARK, { title: 'Keyrook', ink: PAPER }),
  'keyrook-lockup.svg': () => markSvg(LOCKUP_HORIZONTAL, { title: 'Keyrook' }),
  'keyrook-lockup-on-dark.svg': () => markSvg(LOCKUP_HORIZONTAL, { title: 'Keyrook', ink: PAPER }),
  'keyrook-lockup-stacked.svg': () => markSvg(LOCKUP_STACKED, { title: 'Keyrook' }),
  'keyrook-lockup-stacked-on-dark.svg': () => markSvg(LOCKUP_STACKED, { title: 'Keyrook', ink: PAPER }),
  // Products. Each has its own mark; none wears the crow.
  'authenticator-mark.svg': () => markSvg(AUTHENTICATOR_MARK, { title: 'Keyrook Authenticator' }),
  'authenticator-mark-compact.svg': () => markSvg(AUTHENTICATOR_MARK_COMPACT, { title: 'Keyrook Authenticator' }),
  // The interface icons: one file each, and all of them as <symbol>s for <use href="#kr-copy">.
  ...Object.fromEntries(
    Object.keys(ICONS).map((name) => [`icons/${name}.svg`, () => iconSvg(name, { title: name.replace(/-/g, ' ') })]),
  ),
  'keyrook-icons.svg': () =>
    [
      '<svg xmlns="http://www.w3.org/2000/svg">',
      ...Object.keys(ICONS).map(
        (name) =>
          `<symbol id="kr-${name}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${LINE.pen}" stroke-linecap="round" stroke-linejoin="round">${iconElements(name)}</symbol>`,
      ),
      '</svg>',
    ].join('\n'),
};

const PNGS = {
  'keyrook-mark-512.png': () => renderPng(MARK_FULL, { width: 512, sticker: true }),
  'keyrook-mark-1024.png': () => renderPng(MARK_FULL, { width: 1024, sticker: true }),
  // A profile picture: the crow on paper, filling the circle a platform crops to.
  'keyrook-avatar-1024.png': () =>
    renderPng({ ...MARK_FULL, view: [-6, 1, 116, 116] }, { width: 1024, background: PAPER }),
  'keyrook-lockup-1200.png': () => renderPng(LOCKUP_HORIZONTAL, { width: 1200 }),
  'keyrook-lockup-on-dark-1200.png': () => renderPng(LOCKUP_HORIZONTAL, { width: 1200, ink: PAPER }),
  'keyrook-lockup-stacked-1024.png': () => renderPng(LOCKUP_STACKED, { width: 1024 }),
  'authenticator-mark-512.png': () => renderPng(AUTHENTICATOR_MARK, { width: 512 }),
};

// --- guide.html ---------------------------------------------------------------

function swatch(hex, label) {
  return `<div class="sw"><div class="chip" style="background:${hex}"></div><b>${label}</b><code>${hex}</code></div>`;
}

function guide(cssText) {
  const ramps = Object.entries(CRAYON)
    .map(
      ([name, ramp]) =>
        `<div class="ramp"><b>${name}</b><div class="stops">${Object.entries(ramp)
          .map(
            ([stop, hex]) =>
              `<div title="${hex}" style="background:${hex};color:${Number(stop) >= 500 && name !== 'yellow' ? PAPER : INK}">${stop}</div>`,
          )
          .join('')}</div></div>`,
    )
    .join('');
  const neutrals = Object.entries(NEUTRAL)
    .map(([stop, hex]) => `<div title="${hex}" style="background:${hex};color:${Number(stop) >= 500 ? PAPER : INK}">${stop}</div>`)
    .join('');
  const roles = Object.entries(ROLES)
    .map(
      ([role, { crayon, light, dark }]) =>
        `<tr><td><b>${role}</b></td><td>${crayon}</td><td><span class="dot" style="background:${CRAYON[crayon][light]}"></span>${light} <code>${CRAYON[crayon][light]}</code></td><td><span class="dot" style="background:${CRAYON[crayon][dark]}"></span>${dark} <code>${CRAYON[crayon][dark]}</code></td></tr>`,
    )
    .join('');
  const drawn = (mark, options) => markSvg(mark, { ink: 'currentColor', ...options });
  const samples = {
    display: 'Keep the key',
    h1: 'Move to a new phone',
    h2: "Sync the server can't read",
    h3: 'Your recovery key',
    h4: 'Last backed up yesterday at 21:04',
    'body-lg': 'Every code is sealed on this device before it leaves. The server keeps closed boxes and no key.',
    body: 'Scan the QR code on the page you have open, or paste the secret. The account appears with a six-digit code that changes every 30 seconds.',
    small: 'Last signed in on Chrome, Mac, two hours ago.',
    caption: 'Captions, labels, footers. Never smaller than 12.',
    'code-xl': '482 913',
    code: '073 518',
    'code-sm': 'K7QF-2MXA-9P4D-HT3R',
  };
  const scale = Object.entries(TYPE)
    .map(
      ([name, t]) =>
        `<tr><td><code>.kr-${name}</code></td><td><code>${t.size}/${t.line} · ${t.weight}${t.tracking ? ` · ${t.tracking}em` : ''}</code></td><td class="kr-${name}">${samples[name]}</td></tr>`,
    )
    .join('');
  const lettered = (text, width) => drawn(letter(text), { width, title: text });
  const icons = Object.entries(ICON_GROUPS)
    .map(
      ([group, names]) =>
        `<h3>${group[0].toUpperCase()}${group.slice(1)}</h3><div class="icons">${names
          .map((name) => `<figure>${iconSvg(name, { size: 24 })}<figcaption>${name}</figcaption></figure>`)
          .join('')}</div>`,
    )
    .join('\n');
  const space = Object.entries(SPACE)
    .map(([step, px]) => `<tr><td><code>--kr-space-${step}</code></td><td><code>${px}px</code></td><td><span class="bar" style="width:${px}px"></span></td></tr>`)
    .join('');

  return `<!doctype html>
<!-- Generated by scripts/render-brand.mjs from packages/brand/src. Do not edit. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Keyrook brand</title>
<style>
${cssText.replace(HEADER, '').trim()}

* { box-sizing: border-box; }
body { margin: 0; background: var(--kr-page); color: var(--kr-text); font: 16px/1.6 var(--kr-font-sans); }
main { max-width: 960px; margin: 0 auto; padding: 48px 16px 96px; }
h1 { font-size: 32px; font-weight: 600; margin: 24px 0 8px; }
h2 { font-size: 22px; font-weight: 600; margin: 64px 0 8px; padding-top: 16px; border-top: 2px solid var(--kr-line); }
h3 { font-size: 16px; font-weight: 600; margin: 24px 0 8px; }
p, li { max-width: 68ch; }
.muted { color: var(--kr-text-muted); }
code { font-family: var(--kr-font-mono); font-size: 13px; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin: 16px 0; }
.tile { border: var(--kr-line-pen) solid var(--kr-line); padding: 20px; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 12px; min-height: 200px; }
.tile.paper { background: ${PAPER}; color: ${INK}; }
.tile.night { background: ${NIGHT}; color: ${PAPER}; }
.tile.photo { background: repeating-linear-gradient(45deg, ${CRAYON.blue[300]} 0 14px, ${CRAYON.green[300]} 14px 28px); color: ${INK}; }
.tile small { font-size: 13px; opacity: .8; }
.tile svg { max-width: 100%; height: auto; }
.sizes { display: flex; gap: 20px; align-items: flex-end; flex-wrap: wrap; }
.sw { display: flex; flex-direction: column; gap: 2px; }
.chip { height: 72px; border: 1px solid var(--kr-line); margin-bottom: 6px; }
.ramp { margin: 12px 0; }
.stops { display: grid; grid-template-columns: repeat(10, 1fr); }
.stops div { height: 48px; display: flex; align-items: end; padding: 4px; font: 11px var(--kr-font-mono); }
table { border-collapse: collapse; width: 100%; font-size: 14px; }
td, th { text-align: start; padding: 8px; border-bottom: 1px solid var(--kr-line); }
.dot { display: inline-block; width: 12px; height: 12px; border-radius: 50%; margin-inline-end: 6px; vertical-align: -1px; }
.dont { border-color: ${CRAYON.red[500]}; }
.dont small::before { content: "✕ "; color: ${CRAYON.red[600]}; font-weight: 700; }
.do small::before { content: "✓ "; color: ${CRAYON.green[600]}; font-weight: 700; }
.code { font: 600 34px var(--kr-font-mono); letter-spacing: 3px; }
.sketchbox { border: var(--kr-line-pen) solid var(--kr-text); padding: 16px 20px; }
button.kr { font: inherit; background: var(--kr-action); color: ${PAPER}; border: 0; padding: 10px 18px; cursor: pointer; }
.replay { font: inherit; font-size: 14px; background: none; border: 1px solid var(--kr-line); color: inherit; padding: 6px 12px; cursor: pointer; border-radius: 6px; }
.scale td { vertical-align: baseline; }
.scale td:last-child { overflow-wrap: anywhere; }
.alphabet { display: flex; flex-direction: column; gap: 4px; align-items: flex-start; }
.icons { display: grid; grid-template-columns: repeat(auto-fill, minmax(104px, 1fr)); gap: 8px; margin: 8px 0 24px; }
.icons figure { margin: 0; border: 1px solid var(--kr-line); padding: 16px 6px 10px; display: flex; flex-direction: column; align-items: center; gap: 10px; }
.icons figcaption { font: 11px var(--kr-font-mono); color: var(--kr-text-muted); }
.bar { display: inline-block; height: 12px; background: var(--kr-action); border-radius: 3px 1px 3px 1px; }
.lift { background: var(--kr-surface); border: var(--kr-line-pen) solid var(--kr-text); padding: 20px; }
.demo-list { list-style: none; margin: 0; padding: 0; width: 160px; display: flex; flex-direction: column; gap: 6px; }
.demo-list li { height: 14px; background: var(--kr-surface-sunken); border-radius: 3px; }
.hl { position: relative; isolation: isolate; font-size: 22px; font-weight: 600; padding: 0 4px; }
.hl svg { position: absolute; left: -4px; top: 8px; width: calc(100% + 8px); height: calc(100% - 8px); z-index: -1; overflow: visible; }
@media (max-width: 600px) { .stops div { font-size: 0; } }
</style>
</head>
<body>
<main>
${markSvg(LOCKUP_HORIZONTAL, { ink: 'currentColor', width: 300, title: 'Keyrook' }).replace('<svg ', '<svg class="kr-boil" ')}
<h1>Keyrook brand</h1>
<p class="muted">One look for every Keyrook product — Keyrook Authenticator, the website, and the apps after it. Everything on this page is generated from <code>packages/brand/src</code>; the files it shows are in <code>packages/brand/assets</code>, and <code>packages/brand/brand.css</code> gives any page the same colours and movements.</p>

<h2>The crow</h2>
<p>A <i>rook</i> is two things: the chess piece the name suggests, and a bird of the crow family. Crows are known for picking things up and keeping them. Ours keeps a key. Its feathers are four crayons — the colours the product has always had — and its eye is the same yellow as the key.</p>
<p>Keyrook is drawn by hand: ink on paper, crayon colour, lines that wobble a little. It is plain and a bit rough on purpose. A security product that looks like a person made it is easier to trust than one that looks like a vault door.</p>

<h2>Logo</h2>
<div class="grid">
<div class="tile paper">${drawn(MARK_FULL, { width: 140 })}<small>On paper — the default</small></div>
<div class="tile night">${drawn(MARK_FULL, { width: 140 })}<small>On night — the crow turns paper</small></div>
<div class="tile photo">${drawn(MARK_FULL, { width: 140, ink: INK, sticker: true })}<small>Sticker — on anything busy</small></div>
<div class="tile paper">${drawn(MARK_FULL, { width: 140, mono: INK })}<small>One colour — stamps, engraving</small></div>
</div>
<div class="grid">
<div class="tile paper">${drawn(LOCKUP_HORIZONTAL, { width: 280 })}<small>Lockup — headers, the website</small></div>
<div class="tile night">${drawn(LOCKUP_STACKED, { width: 150 })}<small>Stacked — square spaces, splash</small></div>
</div>
<h3>Two drawings, by size</h3>
<p>Below 32 px the compact crow is used: no feet, two broad feathers, a bigger key. At 16 px a foot is a fifth of a pixel and four feathers are one smudge. <code>markFor(px)</code> picks the right one.</p>
<div class="tile paper" style="min-height:0"><div class="sizes">
${[16, 24].map((s) => drawn(MARK_COMPACT, { width: s, sticker: true })).join('')}
${[32, 48, 64, 96, 128].map((s) => drawn(MARK_FULL, { width: s })).join('')}
</div></div>
<h3>Room and size</h3>
<ul>
<li>Clear space round the crow: at least the width of the key on every side.</li>
<li>Smallest: the crow at 16 px (compact), the lockup at 120 px wide. Below that, use the crow alone.</li>
<li>The wordmark is lettered, not typed. Never set "keyrook" in a font to stand in for it.</li>
</ul>
<h3>Don't</h3>
<div class="grid">
<div class="tile paper dont">${drawn(MARK_FULL, { width: 110, ink: CRAYON.blue[500] })}<small>Recolour the crow</small></div>
<div class="tile paper dont" style="transform:none">${drawn(MARK_FULL, { width: 110 }).replace('<svg ', '<svg style="transform:scaleX(1.4)" ')}<small>Stretch it</small></div>
<div class="tile paper dont">${drawn(MARK_FULL, { width: 110, mono: '#4285F4' })}<small>Use Google's colours</small></div>
<div class="tile photo dont">${drawn(MARK_FULL, { width: 110, ink: INK })}<small>Busy ground, no sticker</small></div>
</div>

<h2>The family</h2>
<p>The crow is Keyrook's, and only Keyrook's. It appears where the brand itself speaks: the Keyrook account every product signs in to, the emails it sends, Keyrook's own site, and a small "by Keyrook" at the foot of a product's page. A product never wears it as its icon.</p>
<p>Each product has its own mark, drawn in the same hand with the same four crayons, so the family shows without one member borrowing another's face. Its name is Keyrook and what it does.</p>
<div class="grid">
<div class="tile paper">${drawn(MARK_FULL, { width: 110 })}<small>Keyrook — the brand</small></div>
<div class="tile paper do">${drawn(AUTHENTICATOR_MARK, { width: 110 })}<small>Keyrook Authenticator</small></div>
<div class="tile paper" style="border-style:dashed"><div style="width:110px;height:110px"></div><small>The next product — its own mark</small></div>
</div>
<h3>Keyrook Authenticator</h3>
<p>The countdown asterisk the extension has always had — eight ticks round a centre, like the dial of the 30-second timer every code runs on, and like the asterisks that mask a password — redrawn by hand in Keyrook's crayons. They run blue, yellow, red, green clockwise from twelve — warm pair together, cool pair together: neither Google's order, in either direction, nor Google's colours, which is what keeps eight coloured ticks from reading as theirs. Below 32 px the compact drawing, straighter and thicker. <code>authenticatorMarkFor(px)</code> picks it.</p>
<div class="tile paper" style="min-height:0"><div class="sizes">
${[16, 24].map((s) => drawn(AUTHENTICATOR_MARK_COMPACT, { width: s })).join('')}
${[32, 48, 64, 96, 128].map((s) => drawn(AUTHENTICATOR_MARK, { width: s })).join('')}
</div></div>
<div class="tile night" style="min-height:0"><div class="sizes">
${[16, 24].map((s) => drawn(AUTHENTICATOR_MARK_COMPACT, { width: s })).join('')}
${[32, 48, 64, 96, 128].map((s) => drawn(AUTHENTICATOR_MARK, { width: s })).join('')}
</div></div>
<h3>Don't</h3>
<div class="grid">
<div class="tile paper dont"><div style="display:flex;gap:10px;align-items:center">${drawn(MARK_FULL, { width: 48 })}<b>Keyrook Authenticator</b></div><small>Give a product the crow</small></div>
<div class="tile paper dont"><div style="display:flex;gap:10px;align-items:center">${drawn(AUTHENTICATOR_MARK, { width: 48 })}<b>Keyrook</b></div><small>Call a product just "Keyrook"</small></div>
</div>

<h2>Colour</h2>
<p>Ink and paper first; colour is crayon, used sparingly, and every crayon has one job in every product.</p>
<div class="grid">
${swatch(INK, 'Ink')}${swatch(PAPER, 'Paper')}${swatch(NIGHT, 'Night')}
${Object.entries(CRAYON).map(([name, ramp]) => swatch(ramp[500], name[0].toUpperCase() + name.slice(1))).join('')}
</div>
<h3>Roles</h3>
<table><thead><tr><th>Role</th><th>Crayon</th><th>Text on light</th><th>Text on dark</th></tr></thead><tbody>${roles}</tbody></table>
<p class="muted">Action is blue, danger red, warning yellow, success green — the same in the extension, the site and any app. Red, yellow and green at 500 are too light for text on paper; they colour marks and fills, and text uses the stop in the table, which holds 4.5:1.</p>
<h3>Ramps</h3>
${ramps}
<div class="ramp"><b>neutral</b><div class="stops" style="grid-template-columns:repeat(12,1fr)">${neutrals}</div></div>

<h2>Type</h2>
<p>Keyrook has no handwriting font. The hand shows in what is drawn — the crow, the wordmark, lines and boxes. Words stay in the system's own faces, so all fifty languages look like one product, and none falls back to a stranger's font halfway through a sentence.</p>
<table>
<tr><td><b>Text</b></td><td style="font-family:var(--kr-font-sans)">The quick brown fox — Chữ tiếng Việt — 日本語 — العربية</td></tr>
<tr><td><b>Codes</b></td><td><span class="code">482 913</span></td></tr>
</table>
<p class="muted"><code>--kr-font-sans</code>, <code>--kr-font-mono</code>. Codes, addresses and recovery keys are mono, straight and still: a person reads them and types them somewhere else.</p>
<h3>The scale</h3>
<p>For sites and apps. Each step is a class in <code>brand.css</code>; line heights are even, so text sits on the 4 px beat. The code styles are tabular and always left to right. Tightening is dropped for Arabic, CJK and Thai, and a Vietnamese display heading gets room for a tone stacked on a hat.</p>
<table class="scale">${scale}</table>
<ul>
<li>Sentence case everywhere — headings, buttons, menus. Never all capitals: half the languages the product speaks have no capitals.</li>
<li>Two weights, 400 and 600. Emphasis is 600 or a crayon underline, not italics.</li>
<li>Lines of 45–75 Latin characters, 25–40 CJK. Buttons and labels grow with their words; design with the longest language.</li>
</ul>

<h2>Lettering</h2>
<p>The wordmark's hand, carried on to the whole lower-case alphabet, the digits and the Vietnamese marks. It is drawn, not typed — there is no font file: <code>letter(text)</code> lays the strokes out as a mark, on the wordmark's grid and in its pen, and <code>markSvg</code> writes it with the words as its spoken title.</p>
<div class="tile paper" style="min-height:0">${drawn(letter('keep the key'), { width: 420, title: 'keep the key', drawable: true }).replace('<svg ', '<svg id="letter" class="kr-draw kr-draw-in-turn" ')}<small>Drawn in the order a hand writes it — <code>.kr-draw .kr-draw-in-turn</code></small><button class="replay" data-replay="letter">Again</button></div>
<div class="tile paper alphabet" style="min-height:0">
${lettered('abcdefghijklm', 400)}
${lettered('nopqrstuvwxyz', 380)}
${lettered('0123456789 .,!?', 360)}
${lettered('đơưăâêô', 230)}
${lettered('á à ả ã ạ', 260)}
${lettered('ấ ầ ẩ ẫ ậ', 260)}
${lettered('giữ chìa khoá', 330)}
</div>
<ul>
<li>Display words only: 40 px and up, five words at most, one lettered phrase a screen. <code>letter()</code> refuses more.</li>
<li>Latin and Vietnamese only. A page in any other script sets the same words in its own face at display size, with a crayon underline: the hand is still there.</li>
<li>Never in an interface, and never for a code, an amount, a date or anything a person copies.</li>
<li>Never "keyrook": that is the wordmark, drawn on its own. <code>letter()</code> refuses it.</li>
<li>Ink, or paper on night. One word may take blue, red or green at 500 from 48 px; yellow is for underlines, never letters.</li>
</ul>

<h2>Lines and boxes</h2>
<p>Three pen weights for drawn things — <code>--kr-line-hair</code> ${LINE.hair}px, <code>--kr-line-pen</code> ${LINE.pen}px, <code>--kr-line-marker</code> ${LINE.marker}px at a 24 px icon. A box is drawn by hand with <code>.kr-sketch</code>: four corners that are not quite the same.</p>
<div class="grid">
<div class="sketchbox kr-sketch">A card drawn by hand.</div>
<div><button class="kr kr-sketch-small">Copy code</button></div>
<div class="sketchbox kr-sketch-alt">Its neighbour, turned round: <code>.kr-sketch-alt</code>.</div>
</div>
<p class="muted">Dense lists and tables keep a straight 1 px <code>--kr-line</code>: twenty wobbly lines in a row are noise. Drawn lines are for breaks between sections, one or two a screen. No paper texture: the paper colour is enough, and it prints clean.</p>

<h2>Space and height</h2>
<p>A 4 px beat under everything. The hand is in the lines; the measuring is here, so a drawn interface still lines up and is easy to hit — nothing a finger presses is smaller than 44 × 44.</p>
<table>${space}</table>
<p>Height is cut paper laid on the page: an ink line and a hard shadow down and to the right, never a blur.</p>
<div class="grid">
<div class="lift kr-sketch-small kr-raised"><code>.kr-raised</code> — menus, toasts</div>
<div class="lift kr-sketch kr-floating"><code>.kr-floating</code> — dialogs, sheets, with the page dimmed under ink at 40%</div>
</div>

<h2>Icons</h2>
<p>${Object.keys(ICONS).length} icons, drawn in the same pen on a 24-unit grid with a 20-unit live area. The hand is light, because an icon has to read in half a second at 16 px: a long line sags a little, corners are not all alike, a closed shape closes a touch past where it began. One colour — <code>currentColor</code> — and no fills but dots. Named for what they do, not what they show.</p>
<ul>
<li><code>iconSvg('copy', { size: 20 })</code> writes one with its line set for the size (${Object.entries(ICON_STROKE).map(([size, px]) => `${size} px → ${px}`).join(', ')}); or <code>class="kr-icon kr-icon-20"</code> on any of <code>assets/icons/*.svg</code>, or <code>&lt;use href="keyrook-icons.svg#kr-copy"&gt;</code>.</li>
<li>An icon moves only when its meaning changes (copy → copied: the old one fades, the tick is drawn) or when it says something is under way (sync: its arrows are drawn again). It never spins.</li>
<li>Arrows and chevrons take <code>.kr-icon-flip</code> and point the way a right-to-left page reads.</li>
<li>Other companies' logos are never redrawn in this hand. They come compiled, as their owners drew them, from licensed sets; with none, the service's first letter on a neutral tile.</li>
</ul>
${icons}

<h2>Motion</h2>
<p>Two movements belong to Keyrook, both from hand-drawn animation, and the plain ones under them.</p>
<div class="grid">
<div class="tile paper"><svg id="draw" class="kr-draw" viewBox="0 0 100 60" width="200" fill="none" stroke="${INK}" stroke-width="3" stroke-linecap="round"><path pathLength="1" d="M8 40 C25 10 45 10 55 30 C62 44 78 48 92 22"/></svg><small>Draw — a line drawn in by the pen, once</small><button class="replay" data-replay="draw">Again</button></div>
<div class="tile paper"><div id="boil" class="kr-boil">${drawn(MARK_FULL, { width: 110 })}</div><small>Boil — redrawn a hair out of place, a few times, then still</small><button class="replay" data-replay="boil">Again</button></div>
</div>
<table>
<tr><td><b>fast</b></td><td><code>${MOTION.fast}ms</code></td><td>a press, a toggle</td></tr>
<tr><td><b>base</b></td><td><code>${MOTION.base}ms</code></td><td>a sheet opening, a toast</td></tr>
<tr><td><b>slow</b></td><td><code>${MOTION.slow}ms</code></td><td>a screen arriving</td></tr>
<tr><td><b>draw</b></td><td><code>${MOTION.draw}ms</code></td><td>a line drawn in</td></tr>
<tr><td><b>boil</b></td><td><code>${MOTION.boilStep}ms × 3, ${MOTION.boilRounds} rounds</code></td><td>a drawing settling in</td></tr>
<tr><td><b>ease</b></td><td colspan="2"><code>${MOTION.easeOut}</code></td></tr>
</table>
<ul>
<li>Drawings move; text a person must read never does. A code that wobbles is a code read wrong.</li>
<li>Movement is brief and on arrival. Nothing loops forever except where something is genuinely waiting.</li>
<li>Only transform and opacity: nothing that moves the layout round it.</li>
<li><code>prefers-reduced-motion</code> stops all of it. <code>brand.css</code> already does.</li>
</ul>
<h3>The plain ones</h3>
<table>
<tr><td><b>stagger</b></td><td><code>${MOTION.stagger}ms</code></td><td>between the items of a list arriving; six at most, the rest with the sixth</td></tr>
<tr><td><b>wait</b></td><td><code>${MOTION.wait}ms</code></td><td>before anything says it is waiting — an indicator that flashes and vanishes is worse than none</td></tr>
<tr><td><b>hold</b></td><td><code>${MOTION.hold}ms</code></td><td>how long "Copied" stays</td></tr>
<tr><td><b>toast</b></td><td><code>${MOTION.toast}ms</code></td><td>how long a toast stays, a second more for every ten words</td></tr>
<tr><td><b>ease-in</b></td><td colspan="2"><code>${MOTION.easeIn}</code> — leaving, in about two thirds of the time it took to arrive</td></tr>
<tr><td><b>ease-in-out</b></td><td colspan="2"><code>${MOTION.easeInOut}</code> — something on screen moving between two places</td></tr>
<tr><td><b>settle</b></td><td colspan="2"><code>${MOTION.easeSettle}</code> — a small drawn thing landing like a stamp; never a block of text</td></tr>
<tr><td><b>linear</b></td><td colspan="2">the 30-second countdown, and nothing else: time is linear</td></tr>
</table>
<div class="grid">
<div class="tile paper"><ul id="arrive" class="kr-stagger demo-list"><li></li><li></li><li></li><li></li><li></li></ul><small><code>.kr-stagger</code> — a list arriving</small><button class="replay" data-replay="arrive">Again</button></div>
<div class="tile paper"><div id="pop" class="kr-pop">${iconSvg('success', { size: 48 })}</div><small><code>.kr-pop</code> — landing like a stamp</small><button class="replay" data-replay="pop">Again</button></div>
<div class="tile paper"><span class="hl"><svg id="hl" class="kr-highlight" viewBox="0 0 200 40" preserveAspectRatio="none" aria-hidden="true"><path d="M6 22 C50 17 100 24 150 19 C170 17 186 20 194 18" fill="none" stroke="var(--kr-highlight)" stroke-width="26" stroke-linecap="round" vector-effect="non-scaling-stroke"/></svg>can't read it</span><small><code>.kr-highlight</code> — crayon behind a word</small><button class="replay" data-replay="hl">Again</button></div>
<div class="tile paper">${drawn(AUTHENTICATOR_MARK, { width: 72 }).replace('<svg ', '<svg class="kr-wait" ')}<small><code>.kr-wait</code> — in place of a spinner</small></div>
</div>
<table>
<tr><td><code>.kr-arrive</code>, <code>.kr-stagger</code></td><td>up 8 px out of nothing: a screen, a section, a list</td></tr>
<tr><td><code>.kr-appear</code></td><td>shown in place — a new code fades in where the old one stood; codes never slide, flip or count</td></tr>
<tr><td><code>.kr-leave</code></td><td>going: a fade, quicker than coming</td></tr>
<tr><td><code>.kr-pop</code></td><td>a tick, a badge, a stamp landing</td></tr>
<tr><td><code>.kr-press</code></td><td>anything pressed: down at once, back with a little give</td></tr>
<tr><td><code>.kr-highlight</code></td><td>crayon laid behind a word, after the word has landed</td></tr>
<tr><td><code>.kr-draw-in-turn</code></td><td>with <code>.kr-draw</code>: the strokes one after another — the wordmark, lettering</td></tr>
<tr><td><code>.kr-wait</code></td><td>on the Authenticator mark: its ticks light in turn while something is being waited on</td></tr>
<tr><td><code>.kr-blink</code></td><td>on the crow: one blink, two seconds after its page settles — Keyrook's own pages only</td></tr>
</table>
<p class="muted">A wrong password does not shake the field: the text inside would shake with it. A hand-drawn outline is drawn round the field in red and boils once, and the message fades in under it.</p>

<h2>Words</h2>
<ul>
<li><b>Keyrook</b> is the brand, and names only what Keyrook products share: the account ("a Keyrook account"), the email sender.</li>
<li>Each product is <b>Keyrook</b> + what it does: <b>Keyrook Authenticator</b>. The name is never translated.</li>
<li>Plain and honest about limits. No "military-grade", no "unhackable".</li>
<li>Every word a person reads lives in a language file, the same keys in every language, so all languages say the same thing.</li>
</ul>

<h2>Using it</h2>
<p>In a product in this repository:</p>
<pre><code>import { markFor, markSvg, iconSvg, letter, CRAYON, MOTION } from '@keyrook/brand';
@import '…/packages/brand/brand.css';   /* --kr-* tokens, the type scale, .kr-icon, and every motion on this page */</code></pre>
<p>Anywhere else — keyrook.com copies the kit with its own <code>npm run brand</code> — the files in <code>packages/brand/assets</code> (the icons are in <code>assets/icons</code> and <code>assets/keyrook-icons.svg</code>), <code>brand.css</code>, and the values on this page. Everything in <code>brand.css</code> is a class, so a page that allows one stylesheet and no inline styles can use all of it.</p>
</main>
<script>
document.querySelectorAll('[data-replay]').forEach((button) => {
  button.addEventListener('click', () => {
    const target = document.getElementById(button.dataset.replay);
    const name = target.getAttribute('class');
    target.setAttribute('class', '');
    void target.getBoundingClientRect();
    target.setAttribute('class', name);
  });
});
</script>
</body>
</html>
`;
}

// --- write or check -------------------------------------------------------------

const cssText = css();
const texts = {
  'brand.css': cssText,
  'guide.html': guide(cssText),
  ...Object.fromEntries(Object.entries(SVGS).map(([name, make]) => [`assets/${name}`, `${make()}\n`])),
};

let stale = 0;
for (const [path, content] of Object.entries(texts)) {
  const file = join(OUT, path);
  if (CHECK) {
    let current = null;
    try {
      current = readFileSync(file, 'utf8');
    } catch {}
    if (current !== content) {
      console.error(`✗ ${relative(ROOT, file)} is stale — run node scripts/render-brand.mjs`);
      stale++;
    }
    continue;
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  console.log(`✓ ${relative(ROOT, file)}`);
}

if (CHECK) {
  if (stale) process.exit(1);
  console.log('✓ brand kit is current');
} else {
  for (const [name, make] of Object.entries(PNGS)) {
    const file = join(OUT, 'assets', name);
    writeFileSync(file, make());
    console.log(`✓ ${relative(ROOT, file)}`);
  }
}
