/**
 * Keyrook's design for the static pages under site/ — the intro, the code
 * page, the privacy policy. Each page loads nothing (its Content Security
 * Policy allows no stylesheet or image from anywhere), so what it uses of
 * packages/brand is copied in between markers, from the generated files:
 *
 *   in <style>:  the tokens of brand.css, light and dark
 *   in <svg>:    the icons it names, and the app's mark as #mark
 *
 * Never typed by hand, and a renderer's --check fails when the brand changes
 * and a page has not followed.
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const BRAND = resolve(ROOT, 'packages/brand');

const CSS_BEGIN = '/* @keyrook/brand — copied from packages/brand/brand.css by scripts/site-brand.mjs. Change packages/brand/src. */';
const CSS_END = '/* end of @keyrook/brand */';
const ICONS_BEGIN = /<!-- @keyrook\/brand icons: ([a-z0-9 -]+) -->/;
const ICONS_END = '<!-- end of @keyrook/brand icons -->';

/** The custom properties of brand.css, light and dark: everything before its first class. */
export function brandTokens() {
  const css = readFileSync(resolve(BRAND, 'brand.css'), 'utf8');
  const firstClass = css.search(/^\.kr-/m);
  if (firstClass < 0) throw new Error('packages/brand/brand.css has no classes to stop before.');
  // The comment that introduces the first class belongs to it, not to the tokens.
  const tokens = css.slice(0, firstClass).replace(/\/\*(?:(?!\*\/)[\s\S])*\*\/\s*$/, '');
  return tokens.replace(/^\/\* Generated by[^\n]*\n/, '').trim();
}

/** `<symbol>`s for the names asked: brand icons as #kr-<name>, and `mark` for the app's own. */
function symbols(names, page) {
  const sprite = readFileSync(resolve(BRAND, 'assets/keyrook-icons.svg'), 'utf8');
  return names
    .map((name) => {
      if (name === 'mark') {
        const svg = readFileSync(resolve(BRAND, 'assets/authenticator-mark.svg'), 'utf8');
        const view = svg.match(/viewBox="([^"]+)"/)?.[1];
        const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/<title>[\s\S]*?<\/title>/, '');
        if (!view) throw new Error('authenticator-mark.svg has no viewBox.');
        return `<symbol id="mark" viewBox="${view}">${inner.trim()}</symbol>`;
      }
      const symbol = sprite.match(new RegExp(`<symbol id="kr-${name}"[\\s\\S]*?</symbol>`))?.[0];
      if (!symbol) throw new Error(`${page} asks for the icon "${name}", which packages/brand does not draw.`);
      return symbol;
    })
    .join('\n');
}

/** The page with its brand blocks rewritten. Throws when it has neither. */
export function withBrand(html, page) {
  let out = html;
  let found = false;

  const cssStart = out.indexOf(CSS_BEGIN);
  if (cssStart >= 0) {
    const cssEnd = out.indexOf(CSS_END, cssStart);
    if (cssEnd < 0) throw new Error(`${page}: "${CSS_BEGIN}" has no "${CSS_END}".`);
    out = `${out.slice(0, cssStart)}${CSS_BEGIN}\n${brandTokens()}\n${out.slice(cssEnd)}`;
    found = true;
  }

  const icons = out.match(ICONS_BEGIN);
  if (icons) {
    const start = icons.index + icons[0].length;
    const end = out.indexOf(ICONS_END, start);
    if (end < 0) throw new Error(`${page}: its icon block has no "${ICONS_END}".`);
    out = `${out.slice(0, start)}\n${symbols(icons[1].trim().split(/\s+/), page)}\n${out.slice(end)}`;
    found = true;
  }

  if (!found) throw new Error(`${page} has no @keyrook/brand block to fill.`);
  return out;
}
